services:
  - type: web
    name: infoviz
    runtime: docker
    plan: starter
    region: frankfurt
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/ready
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: VITE_API_URL
        value: ''
      - key: DEBUG
        value: false
      - key: FACTIVERSE_API_TOKEN
        sync: false
